package Vista;

import Controlador.ClienteControlador;
import Modelo.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maryi
 */
public class VistaClientes extends javax.swing.JPanel {

    private final ClienteControlador clienteControlador;
    private Integer idClienteSeleccionada = null;

    /**
     * Creates new form VistaCategorias
     */
    public VistaClientes() {
        initComponents();
        this.clienteControlador = new ClienteControlador();
        cargarDatosTabla();
    }

    private void cargarDatosTabla() {
        List<Cliente> clientes = clienteControlador.obtenerTodosClientes();
        if (clientes != null) {
            DefaultTableModel model = (DefaultTableModel) TablaClientes.getModel();
            model.setRowCount(0);

            for (Cliente cli : clientes) {
                Object[] row = {
                    cli.getIdCliente(),
                    cli.getPrimerNombre(),
                    cli.getSegundoNombre(),
                    cli.getPrimerApellido(),
                    cli.getSegundoApellido(),
                    cli.getCelular(),
                    cli.getDireccion(),
                    cli.getCedula()
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textSegundoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textPrimerNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        textPrimerApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textSegundoApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCelular = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("Primer Nombre");

        textSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSegundoNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Segundo Nombre");

        textPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrimerNombreActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonGuardar(evt);
            }
        });

        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonEliminar(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonActualizar(evt);
            }
        });

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idCliente", "primerNombre", "segundoNombre", "primerApellido", "segundoApellido", "celular", "direccion", "cedula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaClientes);

        jLabel3.setText("Primer Apellido");

        textPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrimerApellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Segundo Apellido");

        textSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSegundoApellidoActionPerformed(evt);
            }
        });

        jLabel5.setText("Celular");

        textDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDireccionActionPerformed(evt);
            }
        });

        jLabel6.setText("Dirección");

        jLabel7.setText("Cedula");

        jLabel8.setText("Buscar");

        jLabel9.setText("Cedula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(textPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrimerNombreActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //  Limpiar(); 
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void textSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSegundoNombreActionPerformed

    private void textPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrimerApellidoActionPerformed

    private void textSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSegundoApellidoActionPerformed

    private void textDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDireccionActionPerformed

    private void accionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonGuardar
        String primerNombre = textPrimerNombre.getText();
        String segundoNombre = textSegundoNombre.getText();
        String primerApellido = textPrimerApellido.getText();
        String segundoApellido = textSegundoApellido.getText();
        String celular = textCelular.getText();
        String direccion = textDireccion.getText();
        String cedula = textCedula.getText();

        if (!primerNombre.isEmpty() && !segundoNombre.isEmpty() && !primerApellido.isEmpty()
                && !primerApellido.isEmpty() && !segundoApellido.isEmpty() && !celular.isEmpty()
                && !direccion.isEmpty() && !cedula.isEmpty()) {

            clienteControlador.crearCliente(primerNombre, segundoNombre, primerApellido,
                    segundoApellido, celular, direccion, cedula);
            cargarDatosTabla();

            textPrimerNombre.setText("");
            textSegundoNombre.setText("");
            textPrimerApellido.setText("");
            textSegundoApellido.setText("");
            textCelular.setText("");
            textDireccion.setText("");
            textCedula.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonGuardar

    private void accionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonEliminar
        int filaSeleccionada = TablaClientes.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idCliente = (int) TablaClientes.getValueAt(filaSeleccionada, 0);
            clienteControlador.eliminarCliente(idCliente);
            cargarDatosTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eleminar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionBotonEliminar

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked

        if (evt.getClickCount() == 2) {
            int filaSeleccionada = TablaClientes.getSelectedRow();
            if (filaSeleccionada != -1) {

                idClienteSeleccionada = (int) TablaClientes.getValueAt(filaSeleccionada, 0);
                String primerNombre = (String) TablaClientes.getValueAt(filaSeleccionada, 1);
                String segundoNombre = (String) TablaClientes.getValueAt(filaSeleccionada, 2);
                String primerApellido = (String) TablaClientes.getValueAt(filaSeleccionada, 3);
                String segundoApellido = (String) TablaClientes.getValueAt(filaSeleccionada, 4);
                String celular = (String) TablaClientes.getValueAt(filaSeleccionada, 5);
                String direccion = (String) TablaClientes.getValueAt(filaSeleccionada, 6);
                String cedula = (String) TablaClientes.getValueAt(filaSeleccionada, 7);

                textPrimerNombre.setText(primerNombre);
                textSegundoNombre.setText(segundoNombre);
                textPrimerApellido.setText(primerApellido);
                textSegundoApellido.setText(segundoApellido);
                textCelular.setText(celular);
                textDireccion.setText(direccion);
                textCedula.setText(cedula);

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void accionBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonActualizar

        String primerNombre = textPrimerNombre.getText();
        String segundoNombre = textSegundoNombre.getText();
        String primerApellido = textPrimerApellido.getText();
        String segundoApellido = textSegundoApellido.getText();
        String celular = textCelular.getText();
        String direccion = textDireccion.getText();
        String cedula = textCedula.getText();

        if (idClienteSeleccionada != null && !primerNombre.isEmpty() && !segundoNombre.isEmpty()
                && !primerApellido.isEmpty() && !segundoApellido.isEmpty() && !celular.isEmpty()
                && !direccion.isEmpty() && !cedula.isEmpty()) {

            clienteControlador.actualizarCliente(idClienteSeleccionada, primerNombre, segundoNombre, primerApellido, segundoApellido, celular, direccion, cedula);
            cargarDatosTabla();

            textPrimerNombre.setText("");
            textSegundoNombre.setText("");
            textPrimerApellido.setText("");
            textSegundoApellido.setText("");
            textCelular.setText("");
            textDireccion.setText("");
            textCedula.setText("");

            btnEliminar.setEnabled(true);
            btnGuardar.setEnabled(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_accionBotonActualizar

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped

        String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Cliente> clientes = clienteControlador.obtenerTodosClientes();

        DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();
        modelo.setRowCount(0);

        if (clientes != null) {
            for (Cliente cli : clientes) {
                if (textoBusqueda.isEmpty()
                        || cli.getPrimerNombre().toLowerCase().contains(textoBusqueda)
                        || cli.getSegundoNombre().toLowerCase().contains(textoBusqueda)
                        || cli.getPrimerApellido().toLowerCase().contains(textoBusqueda)
                        || cli.getSegundoApellido().toLowerCase().contains(textoBusqueda)
                        || cli.getCelular().toLowerCase().contains(textoBusqueda)
                        || cli.getDireccion().toLowerCase().contains(textoBusqueda)
                        || cli.getCedula().toLowerCase().contains(textoBusqueda)) {
                    Object[] fila = {
                        cli.getIdCliente(),
                        cli.getPrimerNombre(),
                        cli.getSegundoNombre(),
                        cli.getPrimerApellido(),
                        cli.getSegundoApellido(),
                        cli.getCelular(),
                        cli.getDireccion(),
                        cli.getCedula(),
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }//GEN-LAST:event_textBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaClientes;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textCelular;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textPrimerApellido;
    private javax.swing.JTextField textPrimerNombre;
    private javax.swing.JTextField textSegundoApellido;
    private javax.swing.JTextField textSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
